common: &common
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password:
  socket: <%= %w[/opt/local/var/run/mysql5/mysqld.sock
                 /var/lib/mysql/mysql.sock
                 /var/lib/mysqld/mysqld.sock
                 /tmp/mysql.sock].find { |socket| File.exist?(socket) } %>

development:
  <<: *common
  database: minimetre_development

test:
  <<: *common
  database: minimetre_test